server:
  port: 8000

spring:
  application:
    name: provider

  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh



my-value: guoduo-1218
